apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -o ./k8s
    kompose.service.type: LoadBalancer
    kompose.version: 1.21.0 (992df58d8)
  creationTimestamp: null
  labels:
    io.kompose.service: zeppelin-hive
  name: zeppelin-hive
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: zeppelin-hive
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -o ./k8s
        kompose.service.type: LoadBalancer
        kompose.version: 1.21.0 (992df58d8)
      creationTimestamp: null
      labels:
        io.kompose.service: zeppelin-hive
    spec:
      containers:
      - env:
        - name: ZEPPELIN_ADDR
          value: 0.0.0.0
        - name: ZEPPELIN_INTERPRETER_DEP_MVNREPO
          value: https://repo1.maven.org/maven2/
        - name: ZEPPELIN_PORT
          value: "18888"
        image: loum/zeppelin-hive:latest
        imagePullPolicy: ""
        name: zeppelin-hive
        ports:
        - containerPort: 18888
        resources: {}
      restartPolicy: Always
      serviceAccountName: ""
      volumes: null
status: {}
