apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert -o ./k8s
    kompose.service.type: LoadBalancer
    kompose.version: 1.21.0 (992df58d8)
  creationTimestamp: null
  labels:
    io.kompose.service: zeppelin-hive
  name: zeppelin-hive
spec:
  ports:
  - name: "18888"
    port: 18888
    targetPort: 18888
  selector:
    io.kompose.service: zeppelin-hive
  type: LoadBalancer
status:
  loadBalancer: {}
